definitions:
  utils.CreateNoteForm:
    properties:
      content:
        type: string
      title:
        type: string
      urls:
        type: string
    required:
    - content
    - title
    type: object
  utils.GetNoteInfoFrom:
    properties:
      note_identity:
        type: string
    required:
    - note_identity
    type: object
  utils.H:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  utils.LoginForm:
    properties:
      password:
        type: string
      repassword:
        type: string
      username:
        type: string
    required:
    - password
    - repassword
    - username
    type: object
  utils.ModifyPasswordForm:
    properties:
      password:
        type: string
      repassword:
        type: string
      username:
        type: string
    required:
    - password
    - repassword
    - username
    type: object
  utils.ModifyUserInfoForm:
    properties:
      age:
        type: string
      sex:
        type: string
      url:
        type: string
      username:
        type: string
    required:
    - age
    - sex
    - url
    - username
    type: object
  utils.RegisterForm:
    properties:
      code:
        type: string
      email:
        type: string
      password:
        type: string
      repassword:
        type: string
      username:
        type: string
    required:
    - code
    - email
    - password
    - repassword
    - username
    type: object
  utils.SendCodeForm:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  utils.UserModifyPasswordForm:
    properties:
      nowpassword:
        type: string
      password:
        type: string
      repassword:
        type: string
    required:
    - nowpassword
    - password
    - repassword
    type: object
  utils.VerifyEmailCodeForm:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
info:
  contact: {}
paths:
  /capacha/get:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 获取验证码
      tags:
      - 登录业务接口
  /capacha/verify:
    get:
      parameters:
      - description: capachaId
        in: query
        name: capachaId
        required: true
        type: string
      - description: capachaVal
        in: query
        name: capachaVal
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 验证验证码
      tags:
      - 登录业务接口
  /forgetPassword/modifyPassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.ModifyPasswordForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 密码修改
      tags:
      - 登录业务接口
  /forgetPassword/verifyEmailCode:
    post:
      consumes:
      - application/json
      parameters:
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.VerifyEmailCodeForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 忘记密码-验证验证码
      tags:
      - 登录业务接口
  /getNoteInfo:
    post:
      consumes:
      - application/json
      parameters:
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.GetNoteInfoFrom'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 获取帖子详细信息
      tags:
      - 公共接口
  /hello:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 首页
      tags:
      - 公共接口
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 用户登录
      tags:
      - 登录业务接口
  /note/createNote:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.CreateNoteForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 创建帖子
      tags:
      - 帖子业务接口
  /note/deleteNote:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.GetNoteInfoFrom'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 删除帖子
      tags:
      - 帖子业务接口
  /note/getNoteList:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 获取发布帖子列表
      tags:
      - 帖子业务接口
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.RegisterForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 用户注册
      tags:
      - 登录业务接口
  /searchNotes:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 搜索帖子
      tags:
      - 公共接口
  /searchNotesScoreOrTime:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: type
        in: query
        name: type
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 按照热度或时间获取帖子信息
      tags:
      - 公共接口
  /sendEmailCode:
    post:
      consumes:
      - application/json
      parameters:
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.SendCodeForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 发送邮件验证码
      tags:
      - 登录业务接口
  /uploadLocal:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      - description: 文件类型
        in: formData
        name: type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 上传图片
      tags:
      - 公共接口
  /user/getUserInfo:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 获取用户信息
      tags:
      - 用户业务接口
  /user/modifyUserInfo:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.ModifyUserInfoForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 修改用户信息
      tags:
      - 用户业务接口
  /user/userModifyPassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 发送参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/utils.UserModifyPasswordForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.H'
      summary: 更换密码
      tags:
      - 用户业务接口
swagger: "2.0"
